### ISSUE TITLE
error:must have a valid type

### ISSUE THREAD

**Issue by askie** [gofullstack/gearman-node#3]
/home/wwwroot/sv.autobloglink.com/node_modules/gearman/lib/packet.js:56
    if (!o.type) { throw Error("must have a valid type"); }
                         ^
Error: must have a valid type
    at Error (unknown source)
    at Object.decode (/home/wwwroot/cmmd/node_modules/gearman/lib/packet.js:56:26)
    at Socket.<anonymous> (/home/wwwroot/cmmd/node_modules/gearman/lib/client.js:35:27)
    at Socket.emit (events.js:67:17)
    at TCP.onread (net.js:367:14)

system:
node 0.6.18
centos 5.7 64bit

this error show more times

**Comment by smith** [comment]
Can you link to a gist or something with an example of how this error is being triggered?
